### ISSUE TITLE
Create dotfiles for workplace-issued MacBook Pro

### ISSUE THREAD

**Issue by addianto** [addianto/dotfiles#7]
# Description

I was loaned a MacBook Pro (2017) recently at my workplace. Would be great if I have my own custom configuration. If possible, make the dotfiles to be generic so that it can be reused in Windows (via Cygwin/WSL) and Linux VM.

## Tasks

- [x] Prepare `.macos` that prepares sensible macOS default setting
- [x] Prepare `.editorconfig` that prepares default EditorConfig setting at home directory
- [x] Prepare `.gitignore` that prepares default Git ignore configuration at home directory
- [x] Prepare `.gitconfig` that prepares default Git configuration at home directory
- [x] Prepare `brew.sh` for installing packages and apps via Homebrew

## References

- https://github.com/mathiasbynens/dotfiles
